### ISSUE TITLE
Robot's trajectory problem

### ISSUE THREAD

**Issue by ZhangLiang-Cencen** [DRCL-USC/Hector_Simulation#1]
Thanks for your good work!
But some problems occurred when I ran the code.
When I press the start button, the robot's trajectory becomes chaotic.
![Screenshot from 2023-10-17 18-10-19](https://github.com/DRCL-USC/Hector_Simulation/assets/54580468/2ea37df1-7663-4964-995c-4c6084fca518)

**Comment by robotlinker** [comment]
I have a similar problem.

**Comment by ZhangLiang-Cencen** [comment]
I have solved the problem through the following suggestion:
In some occasions the controller does not kick in after starting, please terminate the controller with ctrl + \. Then go back to the simulator, pause, and reset (ctrl + R). Rerun controller.
