### ISSUE TITLE
Problems about rotation matrix and euler angle 

### ISSUE THREAD

**Issue by BIT-XLJ** [DRCL-USC/Hector_Simulation#10]
Thanks for your great job!
But when I read your source code, I find something wired. 
![2023-12-12 17-00-41屏幕截图](https://github.com/DRCL-USC/Hector_Simulation/assets/60477639/10084afa-0f60-4dcf-839c-5092958d5199)
In the file SolverMPC.cpp, why you first obtain Euler angle from Quaternion, and then get rotation matrix from euler angle? Why use this instead of rs.R_yaw? And when I use rs.R_yaw, the simulation will fail. But as described in your essay, the rotation matrix should be rs.R_yaw.
Also, I don't know the function euler_to_rotation().
![2023-12-12 17-15-32屏幕截图](https://github.com/DRCL-USC/Hector_Simulation/assets/60477639/3d98c582-e641-4397-a8ff-b34859293e3b)
Why the return value is this?What is the physical meaning behind the return value?

**Comment by junhengl** [comment]
Hello, thanks for the questions. We found using Ryaw in rotation dynamics is not accurate enough for highly dynamic 3D motions. As indicated in the code, Rb represents the rotation dynamics mapping between rate of change of Euler angles and angular velocity. The difference between Rb and Ryaw is Ryaw has further assumption of small and negligible roll and pitch angles. We will rewrite this part for more clarity, sorry for the confusion.
