### ISSUE TITLE
About the horizonLength of MPC controllor

### ISSUE THREAD

**Issue by gaiyi7788** [DRCL-USC/Hector_Simulation#12]
Outstanding work!

I hope to try changing the horizonLength of the MPC controllor to see how the controllor works. However, when I turn the horizonLength to less than 10, the following error happened:

`hector_ctrl: malloc.c:4036: _int_malloc: Assertion (unsigned long) (size) >= (unsigned long) (nb) failed.`

Could you give me some advice, thank you!

**Comment by junhengl** [comment]
Hi there, this code structure is not really meant to be used with shorter than 10 horizon length. You may want to rewrite some of the gait planning and contact schedule section of the code to reach this autonomy. Feel free to modify those in convexMPCLocomotion.cpp

**Comment by gaiyi7788** [comment]
Got it! Thank you for the timely reply!
