### ISSUE TITLE
moving forward failed in simulink

### ISSUE THREAD

**Issue by Decdestiny001** [DRCL-USC/Hector_Simulation#16]
Hello,

I set vx = 0.5 (desired x_velocity ) for the Hector in Matlab/simulink without any rotation mode, and it failed to walk after 3 steps. I tried to tune the weight factor in MPC controller, but it still doesn't work. Any suggestion, please?

**Comment by junhengl** [comment]
I have updated a new version that should resolve this problem, please use this lastest version. 
thanks,
Junheng

**Comment by Decdestiny001** [comment]
Hello Junheng,

Problem solved! Thanks a lot!

Chao
