### ISSUE TITLE
Possibility of finger gripper?

### ISSUE THREAD

**Issue by ramkumarkoppu** [DRCL-USC/Hector_Simulation#17]
Hi,

If I want to have finger gripper to the hand, how to use it in this simulator please?

**Comment by junhengl** [comment]
We plan to include a two-finger gripper in the HECTOR V2 simulation for manipulation control. Still working on it, and will have some updates in the next months. If you wish to use it now, please consider manually adding additional joints to the xacro model and updating joint controllers for them as well in ROS.
