### ISSUE TITLE
confusion about the installation position of IMU

### ISSUE THREAD

**Issue by ZY17740963779** [DRCL-USC/Hector_Simulation#18]
thanks for your great work!!!
I am confused about how to determine the installation position of the IMU in the actual robot？

**Comment by junhengl** [comment]
The position of the IMU on the Unitree A1 robot is actually very close to the CoM of the trunk. In the biped form as HECTOR, the IMU is slightly above the battery of the A1 body. In the hardware, we use a fusion of IMU reading and t265 camera reading as our state estimation data.

**Comment by ZY17740963779** [comment]
thanks for your answer!
