### ISSUE TITLE
and there is an problem like that when i press the keyborad up and down key，the robot walk will fall down

### ISSUE THREAD

**Issue by dbdxnuliba** [DRCL-USC/Hector_Simulation#2]
thanks for your nice work
and there is an problem like that when i press the keyborad up and down key，the robot walk will fail
![image](https://github.com/DRCL-USC/Hector_Simulation/assets/13350158/b1abb2a9-bb93-4312-a8a1-4e66ca9fbbfe)

**Comment by yiyuc** [comment]
Hi, in src/interface/keyboard.cpp, we defined w and s keys for forward and backward velocity commands. We are checking both from the command interface side and the controller side to fix it.

**Comment by junhengl** [comment]
Up and down arrow keys shouldn't do anything. I have tested the other keyboard commands, it seems working fine for me. The only problem was the velocity command when using the keyboard was a bit large, please check out the new update. The keyboard control instruction is also updated in the readme file.
