### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by abnerjie** [DRCL-USC/Hector_Simulation#21]
Hello, I am encountering some issues while compiling my project. When I run catkin_make, I run into a problem. The same problem occurs when I compile with catkin_make -DCMAKE_BUILD_TYPE=Release. The issue is that it prompts with the following message:
"In file included from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/interface/../../include/interface/../sdk/include/unitree_legged_sdk/unitree_legged_sdk.h:12,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/interface/../../include/interface/CmdPanel.h:38,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/interface/../../include/interface/KeyBoard.h:11,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/interface/KeyBoard.cpp:1:
/home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/interface/../../include/interface/../sdk/include/unitree_legged_sdk/lcm.h:9:10: fatal error: lcm/lcm-cpp.hpp: 没有那个文件或目录
    9 | #include <lcm/lcm-cpp.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/build.make:310：Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/src/interface/KeyBoard.cpp.o] 错误 1
make[2]: *** 正在等待未完成的任务....
In file included from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/../interface/../sdk/include/unitree_legged_sdk/unitree_legged_sdk.h:12,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/../interface/CmdPanel.h:38,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/DesiredCommand.h:15,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/ControlFSMData.h:4,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/FSMState.h:6,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/FSM.h:4,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/FSM.cpp:1:
/home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/../interface/../sdk/include/unitree_legged_sdk/lcm.h:9:10: fatal error: lcm/lcm-cpp.hpp: 没有那个文件或目录
    9 | #include <lcm/lcm-cpp.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/../interface/../sdk/include/unitree_legged_sdk/unitree_legged_sdk.h:12,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/../interface/CmdPanel.h:38,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/DesiredCommand.h:15,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/ControlFSMData.h:4,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/FSMState.h:6,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/FSMState.cpp:1:
/home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/../interface/../sdk/include/unitree_legged_sdk/lcm.h:9:10: fatal error: lcm/lcm-cpp.hpp: 没有那个文件或目录
    9 | #include <lcm/lcm-cpp.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/build.make:154：Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/src/FSM/FSM.cpp.o] 错误 1
make[2]: *** [Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/build.make:167：Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/src/FSM/FSMState.cpp.o] 错误 1
In file included from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/../include/common/../interface/../sdk/include/unitree_legged_sdk/unitree_legged_sdk.h:12,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/../include/common/../interface/CmdPanel.h:38,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/../include/common/DesiredCommand.h:15,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/../include/common/ControlFSMData.h:4,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/main.cpp:7:
/home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/../include/common/../interface/../sdk/include/unitree_legged_sdk/lcm.h:9:10: fatal error: lcm/lcm-cpp.hpp: 没有那个文件或目录
    9 | #include <lcm/lcm-cpp.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/build.make:63：Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/src/main.cpp.o] 错误 1
In file included from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/common/../../include/common/../interface/../sdk/include/unitree_legged_sdk/unitree_legged_sdk.h:12,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/common/../../include/common/../interface/CmdPanel.h:38,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/common/../../include/common/DesiredCommand.h:15,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/common/DesiredCommand.cpp:1:
/home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/common/../../include/common/../interface/../sdk/include/unitree_legged_sdk/lcm.h:9:10: fatal error: lcm/lcm-cpp.hpp: 没有那个文件或目录
    9 | #include <lcm/lcm-cpp.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/build.make:219：Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/src/common/DesiredCommand.cpp.o] 错误 1
In file included from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/../interface/../sdk/include/unitree_legged_sdk/unitree_legged_sdk.h:12,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/../interface/CmdPanel.h:38,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/DesiredCommand.h:15,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/ControlFSMData.h:4,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/FSMState.h:6,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/FSMState_Passive.h:4,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/FSMState_Passive.cpp:1:
/home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/../interface/../sdk/include/unitree_legged_sdk/lcm.h:9:10: fatal error: lcm/lcm-cpp.hpp: 没有那个文件或目录
    9 | #include <lcm/lcm-cpp.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/build.make:180：Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/src/FSM/FSMState_Passive.cpp.o] 错误 1
In file included from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/../interface/../sdk/include/unitree_legged_sdk/unitree_legged_sdk.h:12,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/../interface/CmdPanel.h:38,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/DesiredCommand.h:15,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/ControlFSMData.h:4,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/FSMState.h:6,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/FSMState_Walking.h:4,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/FSMState_Walking.cpp:1:
/home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/../interface/../sdk/include/unitree_legged_sdk/lcm.h:9:10: fatal error: lcm/lcm-cpp.hpp: 没有那个文件或目录
    9 | #include <lcm/lcm-cpp.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/build.make:206：Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/src/FSM/FSMState_Walking.cpp.o] 错误 1
In file included from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/common/../../include/common/../../include/common/../interface/../sdk/include/unitree_legged_sdk/unitree_legged_sdk.h:12,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/common/../../include/common/../../include/common/../interface/CmdPanel.h:38,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/common/../../include/common/../../include/common/DesiredCommand.h:15,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/common/../../include/common/../../include/common/ControlFSMData.h:4,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/common/../../include/common/SwingLegController.h:4,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/common/SwingLegController.cpp:1:
/home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/common/../../include/common/../../include/common/../interface/../sdk/include/unitree_legged_sdk/lcm.h:9:10: fatal error: lcm/lcm-cpp.hpp: 没有那个文件或目录
    9 | #include <lcm/lcm-cpp.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/build.make:284：Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/src/common/SwingLegController.cpp.o] 错误 1
In file included from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/ConvexMPC/../include/common/../../include/common/../interface/../sdk/include/unitree_legged_sdk/unitree_legged_sdk.h:12,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/ConvexMPC/../include/common/../../include/common/../interface/CmdPanel.h:38,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/ConvexMPC/../include/common/../../include/common/DesiredCommand.h:15,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/ConvexMPC/../include/common/../../include/common/ControlFSMData.h:4,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/ConvexMPC/../include/common/SwingLegController.h:4,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/ConvexMPC/ConvexMPCLocomotion.h:6,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/ConvexMPC/ConvexMPCLocomotion.cpp:4:
/home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/ConvexMPC/../include/common/../../include/common/../interface/../sdk/include/unitree_legged_sdk/lcm.h:9:10: fatal error: lcm/lcm-cpp.hpp: 没有那个文件或目录
    9 | #include <lcm/lcm-cpp.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/build.make:89：Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/ConvexMPC/ConvexMPCLocomotion.cpp.o] 错误 1
In file included from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/../interface/../sdk/include/unitree_legged_sdk/unitree_legged_sdk.h:12,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/../interface/CmdPanel.h:38,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/DesiredCommand.h:15,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/ControlFSMData.h:4,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/FSMState.h:6,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/FSMState_TO.h:6,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/FSMState_TO.cpp:1:
/home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/FSM/../../include/FSM/../common/../interface/../sdk/include/unitree_legged_sdk/lcm.h:9:10: fatal error: lcm/lcm-cpp.hpp: 没有那个文件或目录
    9 | #include <lcm/lcm-cpp.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/build.make:193：Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/src/FSM/FSMState_TO.cpp.o] 错误 1
In file included from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/interface/../../include/interface/../sdk/include/unitree_legged_sdk/unitree_legged_sdk.h:12,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/interface/../../include/interface/CmdPanel.h:38,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/interface/../../include/interface/IOInterface.h:38,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/interface/../../include/interface/CheatIO.h:7,
                 from /home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/interface/CheatIO.cpp:1:
/home/xie/catkin_ws/src/Hector_Simulation/Hector_ROS_Simulation/hector_control/src/interface/../../include/interface/../sdk/include/unitree_legged_sdk/lcm.h:9:10: fatal error: lcm/lcm-cpp.hpp: 没有那个文件或目录
    9 | #include <lcm/lcm-cpp.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/build.make:297：Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/src/interface/CheatIO.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:9780：Hector_Simulation/Hector_ROS_Simulation/hector_control/CMakeFiles/hector_ctrl.dir/all] 错误 2
make: *** [Makefile:141：all] 错误 2
Invoking "make - -j20 -l20" failed
"

**Comment by yiyuc** [comment]
install lcm from here https://lcm-proj.github.io/lcm/

**Comment by OSKOOO** [comment]
I will close this, feel free to let us know if you run into any trouble.
