### ISSUE TITLE
inertial value of hip2 is not correct

### ISSUE THREAD

**Issue by matheecs** [DRCL-USC/Hector_Simulation#4]
https://github.com/DRCL-USC/Hector_Simulation/blob/958c5e2524250129b912471934aed6726e60db57/Hector_ROS_Simulation/hector_description/xacro/const.xacro#L92

inertia must satisfy A + B >= C, please fix it

**Comment by cyoahs** [comment]
There might be a missing "mirror" in the origin of the inertial for hip and hip2. With the current value the robot is not symmetric...

**Comment by cyoahs** [comment]
There might be a missing "mirror" in the origin of the inertial for hip and hip2. With the current value the robot is not symmetry...

**Comment by junhengl** [comment]
Good catch, we will update the MoI values accordingly, The hip2 plate was oriented incorrectly when grabbing these data.
