### ISSUE TITLE
the robot will fall down once the simulation is start

### ISSUE THREAD

**Issue by dbdxnuliba** [DRCL-USC/Hector_Simulation#9]
![aa](https://github.com/DRCL-USC/Hector_Simulation/assets/13350158/6c49d14d-51f3-4b11-9881-80daa7c8c557)

the terminal show info
'''
Right Hip 1 torque cmd  =  0.147943
Right Hip 2 torque cmd  =  -17.1535
Right Thigh torque cmd  =  3.37865
Right Knee  torque cmd  =  47.6448
Right Toe   torque cmd  =  2.91999
motor joint data0: 0
motor joint data1: 0
motor joint data2: 0
motor joint data3: 0
motor joint data4: 0
motor joint data5: 0
motor joint data6: 0
motor joint data7: 0
motor joint data8: 0
motor joint data9: 0
swing 0: 0.21
Contact 0: 0
swing 1: 0
Contact 1: 0.21
legtau0: 0
legtau1: 0
legtau2: 0
legtau3: 0
legtau4: 0
Left  Hip 1 torque cmd  =  0
Left  Hip 2 torque cmd  =  1.58785
Left  Thigh torque cmd  =  -0.000794176
Left  Knee  torque cmd  =  -2.29608
Left  Toe   torque cmd  =  0
legtau0: 0.147943
legtau1: -17.1535
legtau2: 3.37865
legtau3: 47.6448
legtau4: 2.91999
Right Hip 1 torque cmd  =  0.147943
Right Hip 2 torque cmd  =  -17.1535
Right Thigh torque cmd  =  3.37865
Right Knee  torque cmd  =  47.6448
Right Toe   torque cmd  =  2.91999
motor joint data0: 0
motor joint data1: 0
motor joint data2: 0
motor joint data3: 0
motor joint data4: 0
motor joint data5: 0
motor joint data6: 0
motor joint data7: 0
motor joint data8: 0
motor joint data9: 0
'''

and 
robot@test:~/ws_hector$ rostopic echo /hector_gazebo/L_hip_controller/state 
WARNING: no messages received and simulated time is active.
Is /clock being published?

**Comment by leobince** [comment]
same problem
